name: Manual Update TLE

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-tle
  cancel-in-progress: true

jobs:
  update-tle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Fetch latest TLE
        run: node scripts/update-tle.mjs

      - name: Commit TLE update
        shell: bash
        run: |
          set -euo pipefail

          git add public/tle

          if git diff --cached --quiet; then
            echo "No TLE changes."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git commit -m "Update TLE"

          git pull --rebase origin main
          git push origin HEAD:main
